In [54]:
users = {"Angelica":{"Moderatto":2.5, "Caifanes":2.0, "Heroes del Silencio":4.5,"Soda Estereo":5.0, "Tierra Santa":1.5, "Rata Blanca":2.5, "Mago de Oz":2.0},
    "Bill":{"Moderatto":2.0, "Tierra Santa":3.5,"mago de Oz":3.0,"Lisa Simpson":4.0,"Rata Blanca":2},
        "Chan":{"Moderatto":5.0, "Caifanes":1.0, "La ley":1.0, "Heroes del silencio":3.0,"Soda Estereo": 5.0,"Tierra Santa":1.0},
            "Dan":{"Moderatto":3.0, "Caifanes":4.0, "La Ley": 4.5,"Soda Estereo":3.0, "Tierra Santa":4.5,"Rata Blanca":4.0,"Mago de Oz":2.0},
                "Hailey":{"Caifanes":4.0,"La Ley":1.0,"Heroes del Silencio":4.0,"Rata Blanca":4.0, "Mago de Oz": 1.0},                    
                        "Jordyn":{"Caifanes":4.5, "La Ley": 4.0, "Heroes del Silencio":5.0, "Soda Estereo":5.0,"Tierra Santa": 4.0, "Rata Blanca":5.0},
                                "Sam":{"Moderato":5.0, "Caifanes":2.0, "Heroes del Silencio":5.0,"Soda Estereo":4.0, "Tierra Santa": 4.0},
                                    "Veronica":{"Moderatto":3.0, "Heroes del Silencio":5.0,"Soda Estereo":4.0,"Tierra Santa":2.5, "Rata Blanca":3.0}
                                        }

In [6]:
users.keys()# quienes son los usuarios

['Angelica', 'Veronica', 'Sam', 'Jordyn', 'Dan', 'Bill', 'Chan', 'Hailey']

In [7]:
len(users) #  Numero de usuarios

8

In [8]:
users["Bill"] # Muestra el diccionario de Bills

{'Moderatto': 2.0, 'Tierra Santa': 3.5, 'mago de Oz': 3.0}

In [10]:
users["Bill"].keys() # Muestra el diccionario de Bills sin raiting

['Moderatto', 'mago de Oz', 'Tierra Santa']

In [11]:
users["Bill"].values() # Muestra el diccionario de Bills solo valores

[2.0, 3.0, 3.5]

In [14]:
for i in users["Bill"].keys(): #Muestra las bandas por una lista
    print i
# Conocer la banda con mas Raiting


Moderatto
mago de Oz
Tierra Santa


In [33]:
raiting=6.0 # Muestra el raiting mas alto
maximo = 0.0
for cancion in users["Bill"].keys(): #Muestra las bandas por una lista
    raiting = users["Bill"][cancion]   
    if maximo< raiting:
        maximo=raiting
        maximo=persona
print raiting
print cancion
        
    

3.5
Tierra Santa


In [28]:
# Muestra el raiting mas alto
r = users["Bill"].values()
r.sort()
r.reverse()
for i in users["Bill"].keys(): #Muestra las bandas por una lista
    if users["Bill"][i] == r[0]:
        print i

Tierra Santa


In [56]:


#Saca los valores de raiting
raiting= users["Sam"].values()
print raiting

[2.0, 5.0, 5.0, 4.0, 4.0]


In [58]:
#Crea un vector restando dos vectores del mimso tamaño
import numpy as np
vector =np.array(users["Sam"].values()) - np.array(users["Bill"].values())
vector

array([ 0. ,  1. ,  2. ,  0.5,  2. ])

In [52]:
np.array(users["Sam"].values())

array([ 2.,  5.,  5.,  4.,  4.])

In [53]:
np.array(users["Bill"].values())

array([ 2. ,  4. ,  3. ,  3.5])

In [63]:
#Inteseccion de gustos similares de bill y sam
conjuntoSam = set(users["Sam"].keys())
conjuntoBill = set(users["Bill"].keys())
interseccion =conjuntoSam & conjuntoBill
interseccion
    

{'Tierra Santa'}

In [71]:
for usuario in  users.values(): # Muestra Diccionarios
    print usuario

{'Moderatto': 2.5, 'Soda Estereo': 5.0, 'Rata Blanca': 2.5, 'Tierra Santa': 1.5, 'Caifanes': 2.0, 'Heroes del Silencio': 4.5, 'Mago de Oz': 2.0}
{'Moderatto': 3.0, 'Rata Blanca': 3.0, 'Heroes del Silencio': 5.0, 'Tierra Santa': 2.5, 'Soda Estereo': 4.0}
{'Caifanes': 2.0, 'Moderato': 5.0, 'Heroes del Silencio': 5.0, 'Tierra Santa': 4.0, 'Soda Estereo': 4.0}
{'Soda Estereo': 5.0, 'Rata Blanca': 5.0, 'Tierra Santa': 4.0, 'La Ley': 4.0, 'Caifanes': 4.5, 'Heroes del Silencio': 5.0}
{'Moderatto': 3.0, 'Soda Estereo': 3.0, 'Rata Blanca': 4.0, 'Tierra Santa': 4.5, 'La Ley': 4.5, 'Caifanes': 4.0, 'Mago de Oz': 2.0}
{'Moderatto': 2.0, 'Lisa Simpson': 4.0, 'mago de Oz': 3.0, 'Tierra Santa': 3.5, 'Rata Blanca': 2}
{'Moderatto': 5.0, 'Soda Estereo': 5.0, 'Tierra Santa': 1.0, 'La ley': 1.0, 'Caifanes': 1.0, 'Heroes del silencio': 3.0}
{'Caifanes': 4.0, 'Rata Blanca': 4.0, 'Heroes del Silencio': 4.0, 'La Ley': 1.0, 'Mago de Oz': 1.0}


In [75]:
for usuario in  users.values(): # Muestra Diccionarios
    for bandas in usuario:
        print bandas

Moderatto
Soda Estereo
Rata Blanca
Tierra Santa
Caifanes
Heroes del Silencio
Mago de Oz
Moderatto
Rata Blanca
Heroes del Silencio
Tierra Santa
Soda Estereo
Caifanes
Moderato
Heroes del Silencio
Tierra Santa
Soda Estereo
Soda Estereo
Rata Blanca
Tierra Santa
La Ley
Caifanes
Heroes del Silencio
Moderatto
Soda Estereo
Rata Blanca
Tierra Santa
La Ley
Caifanes
Mago de Oz
Moderatto
Lisa Simpson
mago de Oz
Tierra Santa
Rata Blanca
Moderatto
Soda Estereo
Tierra Santa
La ley
Caifanes
Heroes del silencio
Caifanes
Rata Blanca
Heroes del Silencio
La Ley
Mago de Oz


In [80]:
for usuario in  users.values(): # Muestra bandas
    for bandas in usuario:
        if bandas == "La Ley":
            print bandas
            
        

La Ley
La Ley
La Ley


In [85]:
for u in  users.values(): # Muestra Diccionarios
    for i,v  in u.iteritems():
        if i == "la Ley":
            print v
            

In [98]:
lista=[]
for usuario in  users.values(): # Muestra bandas
    for bandas,raiting in usuario.iteritems():
        if bandas == "La Ley":            
            print raiting
            lista.append(raiting)
print "media de valores de raiting para la ley ", np.array(l).mean()            
            

4.0
4.5
1.0
media de valores de raiting para la ley  3.16666666667


In [94]:
l = []
for u in users.values():
    for i,v in u.iteritems():
        if i == "La Ley":
            print v
            l.append(v)
print "media de Raiting dpara la ley ", np.array(l).mean()

4.0
4.5
1.0
media de Raiting dpara la ley  3.16666666667
