# Bienvenidos NumPY Libreria

In [4]:
import numpy as np

# Inicalizamos con Flotante

In [5]:
# Vectores asignados en ceros
p = np.zeros(0)

In [9]:
type(p)

numpy.ndarray

In [10]:
# Vectores asignados en ceros
q=np.ones(10)
print (q)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [12]:
# Buscar valores diferentes de cero
lista = [0,2,6,1,2,5,8,9,0,0,1]
np.nonzero(lista) # Nos regresa los indices que no tiene cero

(array([ 1,  2,  3,  4,  5,  6,  7, 10]),)

In [13]:
# Asignar valores
# cualquier vector y el numero de indice que queremos asignar.
q[5]=2

In [17]:
# Declarar y asignar vectores por rango
r= np.arange(1,100)
print(r)
#----
# Tambien podemos aplicar formular
r= np.arange(1,100) * 0.5
print(r)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[  0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.
   6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5  12.
  12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5  18.
  18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5  24.
  24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5  30.
  30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5  36.
  36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5  42.
  42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5  48.
  48.5  49.   49.5]


# MATRICES



In [27]:
w = np.arange(10).reshape(2,5) #Como queremos mostrarla. Donde Renglon/Columna.. Arange subir o bajar para satisface la matriz

In [28]:
print(w)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [31]:
# Crear matrices Cuadradas y da la entidad.
y = np.eye(30) # asigna la diagonal, matriz unitaria porque funciona con el 1... Jorge.
print(y)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [36]:
# Matrices Dimensionales con ALEATORIOS
n = np.random.random(10)  # Random no funciona SOLO marca Error [[np.random]]


In [37]:
print (n)

[ 0.17639295  0.4649497   0.7317673   0.46423286  0.69231941  0.7544598
  0.11798569  0.54426235  0.9094605   0.9563809 ]


In [38]:
# hackera el metodo para darle una estructura de datos

In [39]:
n = np.random.random((4,4)) 

In [40]:
print (n)

[[ 0.85141127  0.30385048  0.78163014  0.97279789]
 [ 0.93920324  0.34201676  0.85011101  0.27656851]
 [ 0.44901208  0.10630089  0.14498706  0.16573336]
 [ 0.74023726  0.42772503  0.40610908  0.48297523]]


In [41]:
n = np.random.random((4,3,4)) 

In [42]:
print (n)

[[[ 0.8244132   0.20442206  0.86244313  0.67085798]
  [ 0.74006606  0.39778241  0.15992029  0.54356724]
  [ 0.22820438  0.34471108  0.58494252  0.58472292]]

 [[ 0.83090751  0.04098965  0.89555336  0.14493038]
  [ 0.50926639  0.06279733  0.50821553  0.77268394]
  [ 0.42064138  0.56437195  0.34457112  0.53827815]]

 [[ 0.75696749  0.61511509  0.7207838   0.09034901]
  [ 0.92466264  0.82226951  0.63761922  0.53944013]
  [ 0.00496862  0.66404217  0.95173427  0.90840113]]

 [[ 0.93290309  0.95703777  0.04961329  0.54824095]
  [ 0.84457378  0.75766189  0.22175234  0.39653481]
  [ 0.32039316  0.11618508  0.50632233  0.08799932]]]


In [43]:
n = np.random.random((4,3,4)) ### Entre mas dimensiones hay, es mas dificil el manejo de los datos.

In [55]:
# Minimos y maxmimos
print ('Mínimo en N', n.min())

Mínimo en N 0.00619061195967


In [51]:
print ('Máximo en N', n.max())

Máximo en N 0.990455854325


In [53]:
# Obtener las diagonal. Para los sistema de ecuaciones, no decirles a los estudiantes, no querran hacerlo a mano
np.diag(r)

array([[  0.5,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   1. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   1.5, ...,   0. ,   0. ,   0. ],
       ..., 
       [  0. ,   0. ,   0. , ...,  48.5,   0. ,   0. ],
       [  0. ,   0. ,   0. , ...,   0. ,  49. ,   0. ],
       [  0. ,   0. ,   0. , ...,   0. ,   0. ,  49.5]])

In [54]:
# tambien se puede rotación, etc. pero es otra liberria

In [56]:
# Creando matrices Normalizadas
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
# como se normaliza, dividir el numero mas grande
Z = (Z -Zmin)/(Zmax - Zmin)
print(Z)

[[ 1.          0.05469674  0.50682124  0.6121206   0.77630191]
 [ 0.24258493  0.82029069  0.66262792  0.93825071  0.75697255]
 [ 0.07234201  0.54185582  0.83222681  0.31113998  0.08467593]
 [ 0.54853638  0.92508392  0.79446206  0.95193708  0.37498   ]
 [ 0.1787827   0.40912005  0.37753834  0.          0.4944219 ]]


In [62]:
#
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])