In [37]:
import numpy as np

In [35]:
#vectores asignados en ceros
p=np.zeros(10)
print p

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
type(p)

numpy.ndarray

In [7]:
type(p[1])

numpy.float64

In [36]:
#vectores asignados en unos
q=np.ones(10)
print q


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [14]:
lista=[2,6,0,1,0,2,0,7,0,0]
np.nonzero(lista)   #regresa en los indices que no tiene ceros

(array([0, 1, 3, 5, 7]),)

In [17]:
#asignar valores
q[5]=2
print q


[ 1.  1.  1.  1.  1.  2.  1.  1.  1.  1.]


In [16]:
q[20]

IndexError: index 20 is out of bounds for axis 0 with size 10

In [20]:
#declarar  y  asignar vectores por rangos
r=np.arange(1,100)*0.5
print  r


[  0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.
   6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5  12.
  12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5  18.
  18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5  24.
  24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5  30.
  30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5  36.
  36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5  42.
  42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5  48.
  48.5  49.   49.5]


In [24]:
#crear matrices con  rangos
w=np.arange(16).reshape(2,8)
print w


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [23]:
w=np.arange(20).reshape(4,5)
print w

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
#crear matrices cuadradas  matriz identidad
y=np.eye(3)
print y

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [26]:
#matrices dimensionales con valores
n=np.random.random(10)
print n


[ 0.4388885   0.67404765  0.50280431  0.28747972  0.14632701  0.30297786
  0.19473768  0.92490863  0.26933104  0.03444753]


In [27]:
#matrices dimensionales con valores
n=np.random.random((4,3))
print n


[[ 0.60980543  0.46234534  0.57096097]
 [ 0.4716324   0.9322665   0.18598366]
 [ 0.79146332  0.96303993  0.22867773]
 [ 0.31401436  0.53290533  0.94631225]]


In [28]:
#matrices dimensionales con valores
n=np.random.random((4,3,2))
print n


[[[ 0.17975523  0.56523138]
  [ 0.55855106  0.91369279]
  [ 0.88443209  0.90702926]]

 [[ 0.52916625  0.49621427]
  [ 0.69183261  0.82965268]
  [ 0.73081202  0.53554649]]

 [[ 0.77920256  0.84624683]
  [ 0.16784882  0.99051196]
  [ 0.04564847  0.16033203]]

 [[ 0.63418981  0.86949814]
  [ 0.15262098  0.91727753]
  [ 0.34389152  0.02411564]]]


In [29]:
print 'minimo en N ',n.min()

minimo en N  0.0241156435913


In [30]:
print 'maximo en N ',n.max()

maximo en N  0.99051195695


In [31]:
np.diag(r)

array([[  0.5,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   1. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   1.5, ...,   0. ,   0. ,   0. ],
       ..., 
       [  0. ,   0. ,   0. , ...,  48.5,   0. ,   0. ],
       [  0. ,   0. ,   0. , ...,   0. ,  49. ,   0. ],
       [  0. ,   0. ,   0. , ...,   0. ,   0. ,  49.5]])

In [32]:
z=np.random.random((5,5))
zmax, zmin = z.max(), z.min()
z= (z-zmin) / (zmax- zmin)
print z


[[ 0.44597904  0.95516047  0.7150802   0.          0.47903435]
 [ 0.26676152  0.67836948  1.          0.27768917  0.26648987]
 [ 0.4611594   0.59750376  0.07830929  0.8397355   0.71748169]
 [ 0.04958611  0.79837126  0.10338306  0.13675977  0.44144816]
 [ 0.81410912  0.1084901   0.08506277  0.42728049  0.39289454]]


In [34]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [ ]:
import scipy