# Media, Mediana, Moda

Crear datos de ingresos falsos, centrados alrededor de 27,000 con distribución normal y una desviación estándar de 15,000 con 10,000 puntos de datos. Después calculamos la media(promedio) lo cuál debe ser cercano a 27,000.

In [58]:
import numpy as np

In [59]:
ingresos = np.random.normal(27000,15000,10000)
np.mean(ingresos)

26821.948886640901

Agregando un ingreso atípico = 1000000

In [60]:
ingresos = np.append(ingresos,[1000000000])

La media se sesga en:

In [61]:
np.mean(ingresos)

126809.26795984492

Pero la mediana no se ve afectada.

In [62]:
np.median(ingresos)

26644.554179357976

Generando edades falsas par 500 personas

In [63]:
edades = np.random.randint(18, high=90, size=500)

In [64]:
edades

array([41, 72, 82, 58, 20, 23, 42, 50, 50, 39, 62, 21, 81, 27, 71, 36, 89,
       66, 77, 70, 38, 61, 20, 26, 73, 29, 51, 33, 25, 23, 67, 61, 65, 62,
       41, 46, 38, 88, 66, 68, 48, 37, 24, 69, 30, 72, 60, 46, 87, 71, 61,
       72, 72, 32, 63, 82, 62, 67, 81, 72, 86, 28, 86, 53, 27, 88, 40, 49,
       55, 18, 43, 89, 60, 87, 20, 40, 55, 72, 41, 21, 26, 30, 33, 24, 46,
       61, 62, 71, 54, 64, 84, 36, 60, 89, 47, 88, 24, 67, 21, 71, 57, 45,
       48, 49, 59, 70, 32, 21, 58, 26, 73, 46, 48, 77, 61, 25, 87, 21, 67,
       74, 30, 53, 65, 72, 39, 20, 61, 25, 54, 77, 63, 19, 42, 47, 64, 31,
       24, 66, 23, 76, 71, 45, 72, 45, 47, 84, 61, 81, 65, 71, 41, 43, 51,
       19, 59, 27, 23, 44, 64, 82, 50, 74, 18, 70, 68, 81, 32, 68, 81, 44,
       33, 23, 38, 50, 56, 22, 82, 89, 75, 36, 22, 22, 19, 53, 31, 19, 68,
       59, 87, 82, 27, 87, 44, 61, 34, 24, 75, 67, 64, 87, 21, 61, 88, 89,
       46, 29, 72, 62, 71, 42, 54, 85, 77, 78, 58, 36, 86, 83, 61, 85, 24,
       70, 48, 42, 88, 40

In [65]:
from scipy import stats

In [66]:
stats.mode(edades)

ModeResult(mode=array([43]), count=array([13]))

Vamos a agregar un código de datos de comercio electrónico aleatorio; representan la cantidad total de gastos por transacción.

In [67]:
import matplotlib.pyplot as plt

In [68]:
gastos = np.random.normal(100.0,20,10000)
plt.hist(gastos,50)

(array([   1.,    0.,    0.,    2.,    3.,    6.,    8.,   14.,   12.,
          30.,   40.,   52.,   71.,  100.,  150.,  187.,  222.,  285.,
         336.,  361.,  475.,  522.,  531.,  568.,  635.,  614.,  620.,
         607.,  607.,  484.,  466.,  414.,  371.,  300.,  218.,  160.,
         159.,  122.,   65.,   59.,   41.,   31.,   17.,   13.,   13.,
           4.,    2.,    1.,    0.,    1.]),
 array([  19.05369603,   22.22708553,   25.40047503,   28.57386453,
          31.74725402,   34.92064352,   38.09403302,   41.26742252,
          44.44081202,   47.61420151,   50.78759101,   53.96098051,
          57.13437001,   60.30775951,   63.48114901,   66.6545385 ,
          69.827928  ,   73.0013175 ,   76.174707  ,   79.3480965 ,
          82.521486  ,   85.69487549,   88.86826499,   92.04165449,
          95.21504399,   98.38843349,  101.56182298,  104.73521248,
         107.90860198,  111.08199148,  114.25538098,  117.42877048,
         120.60215997,  123.77554947,  126.94893897,  13

Generar datos aleatorios, calcular media, mediana, agregar un outlier y recalcular media y mediana.

In [69]:
datos = np.random.normal(520,60,600)

In [70]:
X = np.mean(datos)
print X

522.66704492


In [71]:
Y=np.median(datos)
print Y

520.221243854


In [72]:
np.append(datos,[1700000700])

array([  4.19744940e+02,   5.23954437e+02,   5.93335396e+02,
         4.95438147e+02,   5.14666997e+02,   4.54125861e+02,
         4.88929733e+02,   4.56045353e+02,   6.28700906e+02,
         5.53309752e+02,   4.87910895e+02,   4.94361519e+02,
         6.33352881e+02,   5.07086531e+02,   4.98442895e+02,
         4.65922666e+02,   4.59398503e+02,   4.57493991e+02,
         5.09591820e+02,   4.74175132e+02,   5.26719135e+02,
         5.40445863e+02,   4.72078476e+02,   5.98609757e+02,
         5.21359320e+02,   5.38130117e+02,   5.97044293e+02,
         4.61715813e+02,   5.54823339e+02,   4.79278796e+02,
         5.20552738e+02,   5.17934421e+02,   6.06485690e+02,
         4.49196693e+02,   4.92767675e+02,   5.53962373e+02,
         5.58742571e+02,   5.46769900e+02,   5.49405635e+02,
         4.68845509e+02,   5.36674534e+02,   4.79428571e+02,
         5.99780128e+02,   5.23959702e+02,   5.15207776e+02,
         5.63133838e+02,   5.26711841e+02,   6.69826530e+02,
         5.16973702e+02,

In [73]:
np.median(datos)

520.22124385419306

In [74]:
np.mean(datos)

522.66704492047893

Ejemplos con distribuciones de datos.
Distribución uniforme
   

In [75]:
valores = np.random.uniform(-10,10,100000)

In [76]:
plt.hist(valores,50)

(array([ 2098.,  1999.,  1993.,  1962.,  1959.,  2007.,  2023.,  2060.,
         2036.,  2049.,  1977.,  1990.,  2003.,  2049.,  1915.,  1951.,
         2005.,  1985.,  2058.,  2000.,  1918.,  1881.,  2056.,  1873.,
         1941.,  1970.,  2012.,  1963.,  2096.,  2155.,  2030.,  1987.,
         1998.,  2030.,  2006.,  1992.,  1951.,  2012.,  1941.,  2002.,
         1980.,  2022.,  1937.,  2017.,  1969.,  2016.,  2082.,  2010.,
         2010.,  2024.]),
 array([ -9.99988463e+00,  -9.59988863e+00,  -9.19989263e+00,
         -8.79989662e+00,  -8.39990062e+00,  -7.99990462e+00,
         -7.59990861e+00,  -7.19991261e+00,  -6.79991661e+00,
         -6.39992060e+00,  -5.99992460e+00,  -5.59992860e+00,
         -5.19993259e+00,  -4.79993659e+00,  -4.39994059e+00,
         -3.99994458e+00,  -3.59994858e+00,  -3.19995258e+00,
         -2.79995657e+00,  -2.39996057e+00,  -1.99996457e+00,
         -1.59996856e+00,  -1.19997256e+00,  -7.99976557e-01,
         -3.99980553e-01,   1.54500840e-05,   

In [77]:
import matplotlib.pyplot as plt

In [78]:
from scipy.stats import norm

In [79]:
x = np.arange(-3,3,0.001)

In [80]:
plt.plot(x, norm.pdf(x))

Distribución exponencial

In [81]:
from scipy.stats import expon

In [82]:
import matplotlib.pyplot as plt

In [83]:
x1 = np.arange(0,10,.001)

In [84]:
plt.plot(x1, expon.pdf(x1))

Distribución binomial

In [85]:
from scipy.stats import binom

In [86]:
n,p = 10,0.5

In [87]:
plt.plot(x1, binom.pmf(x1,n,p))

Distribución de Poisson 

In [88]:
from scipy.stats import poisson

In [89]:
x = np.arange(100,600,0.5)

In [90]:
mu = 500

In [91]:
plt.plot(x,poisson.pmf(x,mu))

In [92]:
plt.savefig('figura.png')

In [93]:
plt.show()

## Visualización de datos.

In [94]:
import numpy as np

In [95]:
import matplotlib.pyplot as plt

In [96]:
n = np.random.uniform(-1,1,100)

In [97]:
m = np.random.uniform(-1,1,100)

In [98]:
plt.subplot(2,2,1)

In [99]:
plt.plot(n, marker='x', color='r', label = 'g(x)')
plt.legend()

In [100]:
plt.plot(m, marker='o', color='g', label = 'f(x)')
plt.legend()

Diagrama de dispersión.

In [101]:
plt.subplot(2,2,2)
plt.scatter(n,m)

Diagrama de pastel (Pie Chart)

In [102]:
labels = 'perros','gatos','pajaros','peces'
sizes = [30,40,10,20]
colors = ['red','green','lightblue','blue']
explode = (0,0.1,0,0.1)
plt.subplot(2,2,3)
plt.pie(sizes,explode=explode,labels=labels, colors=colors,
       autopct='%1.1f%%',shadow=True)

([<matplotlib.patches.Wedge at 0x7ff83fabe350>,
  <matplotlib.text.Text at 0x7ff83f971210>])

Multigraficas en una ventana

In [103]:
plt.show()
